kind: Service
apiVersion: v1
metadata:
  name: nfs-production-cluster
spec:
  ports:
    - name: nfs-tcp
      port: 2049
      targetPort: 2049
      protocol: "TCP"
    - name: nfs-udp
      port: 2049
      targetPort: 2049
      protocol: "UDP"
    - name: mountd-tcp
      port: 20048
      targetPort: 20048
      protocol: "TCP"
    - name: rpcbind-tcp
      port: 111
      targetPort: 111
      protocol: "TCP"
  selector:
    app: nfs-production-cluster


