apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-production
#  annotations:
#    volume.beta.kubernetes.io/mount-options: "discard"
spec:
  storageClassName: nfs-class
  capacity:
    storage: "250Gi"
  accessModes:
    - "ReadWriteOnce"
  gcePersistentDisk:
    fsType: "ext4"
    pdName: "data"