apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-prod-storefront-elastic1
spec:
  storageClassName: standard
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  gcePersistentDisk:
    fsType: "ext4"
    pdName: "prod-storefront-elastic1"
