apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-prod-storefront-elastic2
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi