apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod-storefront-imagecache
spec:
  storageClassName: nfs-class
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.47.240.223
    path: "/exports/storefront/cache-img"