apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prod-storefront-imagecache
spec:
  storageClassName: nfs-class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi


