apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-balancer
spec:
  storageClassName: standard
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    fsType: "ext4"
    pdName: "data"

