apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-storefront-catalog
spec:
  storageClassName: nfs-class
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.47.240.223
    path: "/exports/trgpimtest.kt-team.de/file_storage/catalog"
