apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-storefront-catalog
spec:
  storageClassName: nfs-class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi