kind: Service
apiVersion: v1
metadata:
  name: balancer
spec:
  selector:
    app: balancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  type: LoadBalancer
