apiVersion: apps/v1
kind: Deployment
metadata:
  name: trg-vueloc-storefront
  labels:
    app: trg-vueloc-storefront
  namespace: default
spec:
  replicas: 0
  selector:
    matchLabels:
      app: trg-vueloc-storefront
  template:
    metadata:
      labels:
        app: trg-vueloc-storefront
    spec:
      containers:
      - image: d.kt-team.de/trg/storefront:latest
        imagePullPolicy: Always
        name: trg-vueloc-storefront
        env:
        - name: "storefront_urlapi"
          value: "https://test.trg.kt-team.de"
        - name: "storefront_create_endpoint"
          value: "https://test.trg.kt-team.de/api/cart/create?token={{token}}"
        - name: "storefront_updateitem_endpoint"
          value: "https://test.trg.kt-team.de/api/cart/update?token={{token}}&cartId={{cartId}}"
        - name: "storefront_deleteitem_endpoint"
          value: "https://test.trg.kt-team.de/api/cart/delete?token={{token}}&cartId={{cartId}}"
        - name: "storefront_pull_endpoint"
          value: "https://test.trg.kt-team.de/api/cart/pull?token={{token}}&cartId={{cartId}}"
        - name: "storefront_totals_endpoint"
          value: "https://test.trg.kt-team.de/api/cart/totals?token={{token}}&cartId={{cartId}}"
        - name: "storefront_paymentmethods_endpoint"
          value: "https://test.trg.kt-team.de/api/cart/payment-methods?token={{token}}&cartId={{cartId}}"
        - name: "storefront_shippingmethods_endpoint"
          value: "https://test.trg.kt-team.de/api/cart/shipping-methods?token={{token}}&cartId={{cartId}}"
        - name: "storefront_shippinginfo_endpoint"
          value: "https://test.trg.kt-team.de/api/cart/shipping-information?token={{token}}&cartId={{cartId}}"
        - name: "storefront_collecttotals_endpoint"
          value: "https://test.trg.kt-team.de/api/cart/collect-totals?token={{token}}&cartId={{cartId}}"
        - name: "storefront_deletecoupon_endpoint"
          value: "https://test.trg.kt-team.de/api/cart/delete-coupon?token={{token}}&cartId={{cartId}}"
        - name: "storefront_applycoupon_endpoint"
          value: "https://test.trg.kt-team.de/api/cart/apply-coupon?token={{token}}&cartId={{cartId}}&coupon={{coupon}}"
        - name: "dateFormat"
          value: "HH:mm D/M/YYYY"
        - name: "storefront_image_baseUrl"
          value: "http://127.0.0.1:3000"
        - name: "COLUMNS"
          value: "300"
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
#        volumeMounts:
#        - name: project
#          mountPath: /repo/storefront
#      volumes:
#        - name: project
#          hostPath:
#            path: "/home/tmp/storefront-trg/storefront"
      imagePullSecrets:
      - name: regcred
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
kind: Service
apiVersion: v1
metadata:
  name: trg-vueloc-storefront
spec:
  selector:
    app: trg-vueloc-storefront
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
  externalIPs:
  - 172.17.0.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trg-vueloc-api
  labels:
    app: trg-vueloc-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trg-vueloc-api
  template:
    metadata:
      labels:
        app: trg-vueloc-api
    spec:
      containers:
      - image: d.kt-team.de/trg/api:latest
        imagePullPolicy: Always
        name: trg-vueloc-api
        env:
        - name: "es"
          value: "trg-vueloc-elastic-first:9200"
        - name: "pim_es_host_port"
          value: "trg-pimloc-elastic:9200"
        - name: "pim_web_host_port"
          value: "trg-pimloc-web:80"
        - name: "pim_api_client"
          value: "1_1tws2689qzy88kkw4sw488w0gc48wsgkosskgog0gco884wsg4"
        - name: "pim_api_secret"
          value: "35pcqqwwcw840kc8ksgc40k840g40sggcssckgksoko4ss088s"
        - name: "pim_user"
          value: "admin"
        - name: "pim_password"
          value: "admin"
        - name: "api_magento2_url"
          value: "http://magento2.demo-1.xyz.com"
        - name: "api_magento2_imgUrl"
          value: "http://magento2.demo-1.xyz.com/media"
        - name: "api_magento2_magentoUserName"
          value: "admin"
        - name: "api_magento2_magentoUserPassword"
          value: "kt-teamde1"
        - name: "api_magento2_httpUserName"
          value: ""
        - name: "api_magento2_httpUserPassword"
          value: ""

        - name: "api_magento2_api_url"
          value: "http://demo-magento2.vuestorefront.io/rest"
        - name: "api_magento2_api_consumerKey"
          value: "byv3730rhoulpopcq64don8ukb8lf2gq"
        - name: "api_magento2_api_consumerSecret"
          value: "u9q4fcobv7vfx9td80oupa6uhexc27rb"
        - name: "api_magento2_api_accessToken"
          value: "040xx3qy7s0j28o3q0exrfop579cy20m"
        - name: "api_magento2_api_accessTokenSecret"
          value: "7qunl3p505rubmr7u1ijt7odyialnih9"
        - name: "redis_host"
          value: "trg-vueloc-redis"
        - name: "COLUMNS"
          value: "300"
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: cacheimg
          mountPath: /tmp
        - name: project-api
          mountPath: "/repo/api"
        - name: project-build-dir
          mountPath: "/repo/build"
        - name: configs-cron
          mountPath: "/etc/cron.d/"
      volumes:
        - name: cacheimg
          hostPath:
            path: "/home/tmp/storefront-trg/api/cache-img"
        - name: project-build-dir
          hostPath:
            path: "/home/tmp/storefront-trg/build"
        - name: project-api
          hostPath:
            path: "/home/tmp/storefront-trg/api"
        - name: configs-cron
          configMap:
            name: cron-vueloc-api-config
            defaultMode: 0644
            items:
            - key: cron_vueloc
              path: cron_vueloc_api

      imagePullSecrets:
      - name: regcred
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
kind: Service
apiVersion: v1
metadata:
  name: trg-vueloc-api
spec:
  selector:
    app: trg-vueloc-api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trg-vueloc-elastic-first
  name: trg-vueloc-elastic-first
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trg-vueloc-elastic-first
  template:
    metadata:
      labels:
        app: trg-vueloc-elastic-first
      name: trg-vueloc-elastic-first
    spec:
      containers:
      - image: elasticsearch:5.5.2
        imagePullPolicy: Always
        name: cache
        env:
        - name: "cluster.name"
          value: "docker-cluster"
        - name: "bootstrap.memory_lock"
          value: "true"
        - name: "ES_JAVA_OPTS"
          value: "-Xms512m -Xmx512m"
        - name: "COLUMNS"
          value: "300"
        ports:
        - containerPort: 9200
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: elastic
          mountPath: /usr/share/elasticsearch/data
        - name: configs
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
      volumes:
        - name: elastic
          hostPath:
            path: "/home/tmp/storefront-trg/es1"
        - name: configs
          hostPath:
            path: "/home/tmp/storefront-trg/build/configs/elasticsearch/vueloc/elasticsearch.yml"
      imagePullSecrets:
      - name: regcred
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
kind: Service
apiVersion: v1
metadata:
  name: trg-vueloc-elastic-first
spec:
  selector:
    app: trg-vueloc-elastic-first
  ports:
  - protocol: TCP
    port: 9200
    nodePort: 30921
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trg-vueloc-elastic-second
  name: trg-vueloc-elastic-second
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trg-vueloc-elastic-second
  template:
    metadata:
      labels:
        app: trg-vueloc-elastic-second
      name: trg-vueloc-elastic-second
    spec:
     containers:
      - image: elasticsearch:5.5.2
        imagePullPolicy: Always
        name: cache
        env:
        - name: "cluster.name"
          value: "docker-cluster"
        - name: "bootstrap.memory_lock"
          value: "true"
        - name: "ES_JAVA_OPTS"
          value: "-Xms512m -Xmx512m"
        - name: "discovery.zen.ping.unicast.hosts"
          value: "trg-vueloc-elastic-first"
        - name: "COLUMNS"
          value: "300"
        ports:
        - containerPort: 9200
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: elastic
          mountPath: /usr/share/elasticsearch/data
        - name: configs
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
     volumes:
        - name: elastic
          hostPath:
            path: "/home/tmp/storefront-trg/es2"
        - name: configs
          hostPath:
            path: "/home/tmp/storefront-trg/build/configs/elasticsearch/vueloc/elasticsearch.yml"

     imagePullSecrets:
     - name: regcred
     dnsPolicy: ClusterFirst
     restartPolicy: Always
     schedulerName: default-scheduler
     securityContext: {}
     terminationGracePeriodSeconds: 30
---
kind: Service
apiVersion: v1
metadata:
  name: trg-vueloc-elastic-second
spec:
  selector:
    app: trg-vueloc-elastic-second
  ports:
  - protocol: TCP
    port: 9200
    nodePort: 30922
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trg-vueloc-redis
  name: trg-vueloc-redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trg-vueloc-redis
  template:
    metadata:
      labels:
        app: trg-vueloc-redis
      name: trg-vueloc-redis
    spec:
      containers:
      - image: redis
        imagePullPolicy: Always
        name: trg-vueloc-redis
        env:
        - name: "COLUMNS"
          value: "300"
        ports:
        - containerPort: 6379
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: redis
          mountPath: /data
      volumes:
        - name: redis
          hostPath:
            path: "/home/tmp/storefront-trg/redis/data"
      imagePullSecrets:
      - name: regcred
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
kind: Service
apiVersion: v1
metadata:
  name: trg-vueloc-redis
spec:
  selector:
    app: trg-vueloc-redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    nodePort: 31225
  type: NodePort